name: Enhancement proposal
description: Propose an improvement or new functionality
labels: [ 'enhancement' ]
body:
  - type: markdown
    attributes:
      value: |
        We welcome enhancement proposals!

        This template will help us gather the information we need to discuss your proposal and possibile implementation.
  - type: input
    attributes:
      label: Reference version
      description: Which version of the project do you currently use?
      placeholder: n.n.n
    validations:
      required: true
  - type: textarea
    attributes:
      label: Background and motivation
      description: |
        Please describe the purpose and value of the new functionality:

          * what problem does it solve?
          * which type(s) of projects does it affect?
          * is it specific to some configuration or toolchain?

        Include as many code snippets, CI log fragments, screenshots, etc. you deem useful to illustrate your point.

        For texts spanning more than a few lines, please [create a gist](https://gist.github.com/) and provide a link to it.

        Don't forget to use syntax highlighting for Markdown code blocks. For example:

        ```XML
        <Project>

          <PropertyGroup>
            <IsNicelyColored Condition="'$(HasXMLAfterTheThreeBackticks)' == 'true'">true</IsNicelyColored>
          <PropertyGroup>

        </Project>
        ```

        (GitHub's syntax highlighting supports more languages that would be practical to list here.
        [Here's the complete list.]( https://github.com/github/linguist/blob/master/lib/linguist/languages.yml))
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed enhancement
      description: Please describe the desired behavior, i.e. _what_ should happen, not _how_ or _why_ (that belongs to the next section).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation proposals
      description: |
        If you have an idea (or more than one) about _how_ the desired behavior can be implemented, please explain it here.

        Be as detailed as your knowledge of the project allows.

        Even if you don't know the project internals, feel free to speak your mind here.

        Any level of detail, from "I don't know" to specific code snippets, is fine.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Usage examples
      description: Please provide example code and/or project snippets that highlight how the proposed enhancement will affect user projects.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Risks
      description: |
        Please mention any risks that, to your knowledge, the proposed enhancement might entail:

        * breaking changes
        * performance regressions
        * security issues
        * possible incompatibilities
        * added or changed dependencies
        * etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Please add any additional information you deem useful.
    validations:
      required: false
