name: Build, test, and pack

on:
  push:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]

jobs:
  build_test_pack:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_CLI_UI_LANGUAGE: 'en-US'
    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout with full history so nbgv can compute Git height correctly.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.0
      with:
        global-json-file: global.json
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Set Cake verbosity to Diagnostic if debug logging is enabled
      if: ${{ runner.debug }}
      run: echo "CAKE_PARAMS=--verbosity=Diagnostic" >> $GITHUB_ENV
    - name: Run build script
      run: dotnet cake $CAKE_PARAMS
