name: Build, test, and pack

on:
  push:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]

jobs:
  build_test_pack:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: ${{ runner.debug }}
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_CLI_UI_LANGUAGE: 'en-US'
      CAKE_VERBOSITY: ${{ runner.debug && 'Diagnostic' || 'Normal' }}
    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout with full history so nbgv can compute Git height correctly.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore .NET tools
      shell: cmd
      run: dotnet tool restore
    - name: Run build script
      shell: cmd
      run: dotnet cake --target Pack --verbosity %CAKE_VERBOSITY%
