name: Continuous integration and deployment

on:
  push:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]

jobs:
  build:
    name: Build, test, pack, and deploy
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_CLI_UI_LANGUAGE: 'en-US'
    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Run build script
      env:
        RELEASE_DEPLOYMENT_KEY: ${{ secrets.NUGET_DEPLOYMENT_KEY }}
        PRERELEASE_DEPLOYMENT_KEY: ${{ secrets.MYGET_DEPLOYMENT_KEY }}
      run: dotnet cake
