name: Deploy documentation to GitHub Pages

on: workflow_dispatch

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-pages:
    runs-on: windows-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_CLI_UI_LANGUAGE: 'en-US'
    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout with full history so nbgv can compute Git height correctly.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore .NET tools
      shell: cmd
      run: dotnet tool restore
    - name: Set Cake verbosity to Diagnostic if debug logging is enabled
      if: ${{ runner.debug }}
      shell: cmd
      run: echo CAKE_PARAMS=--verbosity=Diagnostic>>%GITHUB_ENV%
    - name: Run Cake script to build documentation
      shell: cmd
      run: dotnet cake docs.cake --target All %CAKE_PARAMS%
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v2
    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_site/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
