name: Publish a release

on:
  workflow_dispatch:
    inputs:
      versionAdvance:
        description: 'Version advance'
        required: true
        type: choice
        default: 'None'
        options:
        - None
        - Unstable
        - Stable
        - Minor
        - Major
      checkChangelog:
        description: 'Check changelog'
        required: false
        default: true
        type: boolean
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_CLI_UI_LANGUAGE: 'en-US'
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      PRERELEASE_NUGET_SOURCE: 'https://www.myget.org/F/tenacom-preview/api/v3/index.json'
      PRERELEASE_NUGET_KEY: ${{ secrets.MYGET_DEPLOYMENT_KEY }}
      RELEASE_NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'
      RELEASE_NUGET_KEY: ${{ secrets.NUGET_DEPLOYMENT_KEY }}
      VERSION_ADVANCE: ${{ inputs.versionAdvance }}
      CHECK_CHANGELOG: ${{ inputs.checkChangelog }}
    steps:
    - name: Log workflow inputs
      run: |
        echo "Version advance : $VERSION_ADVANCE"
        echo "Check changelog : $CHECK_CHANGELOG"
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout with full history so nbgv can compute Git height correctly.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Set Cake verbosity to Diagnostic if debug logging is enabled
      if: ${{ runner.debug }}
      run: echo "CAKE_PARAMS=--verbosity=Diagnostic" >> $GITHUB_ENV
    - name: Run build script
      run: dotnet cake --target Release $CAKE_PARAMS
